### ISSUE TITLE
Kunne ikke konfigurere

### ISSUE THREAD

**Issue by LTKingChaos** [sindrebroch/ha-elvia#12]
Fra logg:

`Logger: homeassistant.config_entries
Source: custom_components/elvia/models.py:341
Integration: Elvia ([documentation](https://github.com/sindrebroch/ha-elvia), [issues](https://github.com/sindrebroch/ha-elvia/issues))
First occurred: 18:20:54 (2 occurrences)
Last logged: 18:31:16

Error setting up entry Elvia for elvia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/elvia/__init__.py", line 27, in async_setup_entry
    data = await api.meteringpoint()
  File "/config/custom_components/elvia/api.py", line 155, in meteringpoint
    return GridTariffCollection.from_dict(collection)
  File "/config/custom_components/elvia/models.py", line 423, in from_dict
    gridTariff=(GridTariff.from_dict(data["gridTariff"])),
  File "/config/custom_components/elvia/models.py", line 341, in from_dict
    tariffType=(TariffType.from_dict(data["tariffType"])),
TypeError: 'NoneType' object is not subscriptable`

**Comment by sindrebroch** [comment]
Which version are you running? Did it fail on initial setup, or just started failing one day?

If not running the latest beta, could you try to update to [0.3.0b0](https://github.com/sindrebroch/ha-elvia/tree/0.3.0b0)?
