### ISSUE TITLE
Seems to be broken on HA 2024.1

### ISSUE THREAD

**Issue by mariwing** [sindrebroch/ha-elvia#21]
Hi!

After upgrading to 2024.1 the Elvia integration stopped working. I restored a backup (to version 2023.12.4) and it started working again.

Unfortunately I did not keep the logs from 2024.1, but if you want me to I can reinstall that version and get the error messages in the log for you.

**Comment by audun-v** [comment]
Same problem for me. This is the error from the logs.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 1:16:56 PM (1 occurrences)
Last logged: 1:16:56 PM

Error while setting up elvia platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/elvia/sensor.py", line 71, in async_setup_entry
    ElviaMaxHourAverageSensor(coordinator, True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elvia/sensor.py", line 156, in __init__
    super().__init__(coordinator, description, "elvia")
  File "/config/custom_components/elvia/sensor.py", line 97, in __init__
    description.key = f"{key_prefix}_{description.key}"
    ^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'key'
```

**Comment by Beerling** [comment]
I have the same issue, and also the same log entry as @audun-v

**Comment by hillmar** [comment]
Same issue on my install, after updating to 2024.1

**Comment by magnushegge** [comment]
For me the integration stopped working ond january 4th on 22:55. I did not upgrade HA core to 2024.1 until january 5th.
I get the same log message as above. All entities under the elvia integration are "Unavailable".

**Comment by grolub** [comment]
Same issue after update to 2024.1

**Comment by magne74** [comment]
Same here…

**Comment by breiviar** [comment]
Same here...

**Comment by mariwing** [comment]
This seems to be related to this: https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/

I am no Python developer and the Home Assistant code seems very confusing to me. But by changing line 96 and the following lines in the initialize block in sensor.py to this, the integration again works on Home Assistant 2024.1.3. 

        """Initialize."""
        super().__init__(coordinator)
        self.coordinator = coordinator
        self.entity_description = description
        self.attribute = self.entity_description.key.replace(f"{key_prefix}_", "")
        self._attr_unique_id = f"{key_prefix}_{description.key}"
        self._attr_device_info = coordinator._attr_device_info
        self.update_from_data()`

**Comment by breiviar** [comment]
Thank you - works like a charm!

**Comment by magne74** [comment]
And how am I doing that @mariwing ?

**Comment by tordenflesk** [comment]
> And how am I doing that @mariwing ?

Delete the follwing from /custom_components/elvia/sensor.py (Line 97):

        description.key = f"{key_prefix}_{description.key}"

**Comment by magne74** [comment]
Thank you!

But it didn’t help:-(

**Comment by magnushegge** [comment]
Deleting (or commenting out with #) line 97 worked for me. 
After a restart of HA, the integration provided values again. 

Unfortunately, it created all new entities, so the Elvia device now has all the previous entities with an "unavailable" state and new entities with _2 appended to the entity ID and working values.

**Comment by mariwing** [comment]
To avoid duplicates, use the line 

`self._attr_unique_id = f"{key_prefix}_{description.key}" `

as I mentioned. This was previously set from the property that was on line 97 (?) that cause the original bug. Since that property is no longer set - the unique id should be set from the values previously used to set the property.

**Comment by mabahj** [comment]
(Original question removed: I see that you have described the full change further up. Thanks!)

**Comment by SumMarius** [comment]
Solved it for me! Thank you very much.

**Comment by magne74** [comment]
Maybe a stupid question but why is this not fixed yet? I have a new installation and had to do the same tweaks in the sensor.py file.

**Comment by mariwing** [comment]
Probably because the creator has abandoned this project unfortunately.
