### ISSUE TITLE
Add-on stops after reboot, reload the add.on works

### ISSUE THREAD

**Issue by kjetilpp** [sindrebroch/ha-elvia#5]
## Version of the custom_component
v0.1.4
## Configuration
Setup using UI, not yaml.

## Describe the bug
After reboot of HA, the add-on is failing to load at boot. Reloading the add-on solves the problem.
I can reproduce the issue. Maybe allow longer timeout? 
## Debug log

```
Logger: homeassistant.config_entries
Source: custom_components/elvia/api.py:105
Integration: Elvia (documentation, issues)
First occurred: 22:30:41 (1 occurrences)
Last logged: 22:30:41

Error setting up entry Elvia for elvia
Traceback (most recent call last):
  File "/config/custom_components/elvia/api.py", line 81, in api_wrapper
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/elvia/api.py", line 80, in api_wrapper
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/elvia/__init__.py", line 26, in async_setup_entry
    data = await api.meteringpoint()
  File "/config/custom_components/elvia/api.py", line 143, in meteringpoint
    response = await self.post(
  File "/config/custom_components/elvia/api.py", line 58, in post
    return await self.api_wrapper(
  File "/config/custom_components/elvia/api.py", line 105, in api_wrapper
    raise ApiClientException(
custom_components.elvia.api.ApiClientException: Timeout error fetching information from https://elvia.azure-api.net/grid-tariff/digin/api/1/tariffquery/meteringpointsgridtariffs

```

**Comment by sindrebroch** [comment]
Will try to increase the timeout in the next release

**Comment by sindrebroch** [comment]
Timeout has been increased in latest release. Please reopen if the issue persist.
